name: fastapi_vectortilelayer_test
channels:
  - conda-forge
  - defaults
dependencies:
  # core
  - python==3.7
  - pip
  - conda
  # fastapi
  - fastapi
  - uvicorn
  # DB
  - sqlalchemy
  - geoalchemy2
  - alembic
  - mongoengine
  # for handling GeoSpatial data
  - pandas>=1.1
  - geopandas>=0.8
  - gdal=>3.0.4
  - fiona>=1.8.13
  - pyproj>=2.6.1
  - shapely
