name: fastapi_vectortilelayer_test
channels:
  - conda-forge
  - defaults
dependencies:
  # core
  - python==3.7
  - pip
  - conda
  # fastapi
  - fastapi
  - uvicorn
  # DB
  - sqlalchemy
  - geoalchemy2
  - alembic
  - mongoengine
  # GeoSpatial
  - geopandas
  - pandas>=1.1
  - shapely
